import styles from './layout.module.css'
import './global.css'
import Header from '@/component/Header'
import Sidebar from '@/component/Sidebar'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <body>
                <div className={styles.layout}>
                    <Header />
                    <Sidebar />
                    <main className={styles.content}>{children}</main>
                </div>
            </body>
        </html>
    )
}
